[package]
name = "camouflage"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
path = "src/helper.rs"

[dependencies]
wasm-bindgen = "0.2.69"
